#LD	= $(CROSS_COMPILE)ld

obj-m := kaodv.o
kaodv-objs := aodv_dev.o aodv_neigh.o aodv_route.o aodv_thread.o flood_id.o hello.o kernel_route.o module.o packet_in.o packet_out.o packet_queue.o rerr.o rrep.o rreq.o signal.o socket.o task_queue.o timer_queue.o utils.o





