#LD	= $(CROSS_COMPILE)ld

obj-m := caching.o
caching-objs := module.o cacheTable.o cDevice.o cExchange.o cFileRep.o cFileReq.o cFlood.o cFragReq.o cPacketIn.o cReqList.o cSocket.o cTask.o cThread.o cTimer.o cUtils.o





